version: '2'
services:
  mosquitto:
    build:
      context: mosquitto
      dockerfile: Dockerfile
    ports:
      - "8883:8883"

  mosquitto-subscriber:
    build:
      context: mosquitto-client
      dockerfile: Dockerfile.sub
    depends_on: 
      - mosquitto

  mosquitto-publisher:
    build:
      context: mosquitto-client
      dockerfile: Dockerfile.pub
    depends_on:
      - mosquitto
      - mosquitto-subscriber
